### PR TITLE
load commands from file

### PR DESCRIPTION
**Pull request by improbably-you**
feel free to add back in your ascii if you're a big fan.

if you use r""" you will be able to avoid extra symbols and things like \n...

### CODE REVIEW

**Comment by Cyber-Guy1** [comment]
Dear @improbably-you,

Thank you for taking the time to contribute to our project. Your enthusiasm is appreciated!

In order to maintain the project's focus on improving user experience and functionality, we kindly request that you submit pull requests that address critical issues or enhance the project's detectability. While ASCII art and similar content can be entertaining, our priority is to address the most pressing concerns affecting users.

We look forward to your future contributions that align with the project's objectives.

Best regards,
Momen

**Comment by improbably-you** [comment]
I feel like that comment is misleading. I did not contribute any ASCII art. I modularized the code, removed uneccesary calls, conditionals (used arg parses to handle missed required params), useless imports, variables, etc. I also added new functionality. I made suggestions across the board and offered a number of efficiency improvements. It's funny to dismiss it as ASCII art.

**Comment by Cyber-Guy1** [comment]
Hey there!,
Sorry if you misunderstood me, but your comment was having suggestions to
use the string formatting with the ASCII art, and this comment was after
the first one in which you asked for unnecessary imports and this was
already done and also applied some OPSEC enhancements. I think there is no
additional enhancements regarding unused/necessary vars or imports.

**Comment by improbably-you** [comment]
My comment was unrelated to my pull request. There are still issues with the code. If you'd like to see a full list of changes included in this pull request, please don't hesitate to open the commit and read through them yourself 😜

**Comment by Cyber-Guy1** [comment]
In response to your comment, I kindly request that you provide a detailed summary of the issues addressed in your pull request, as it will greatly assist in the review process. Please ensure that your summary includes the following information:

- The origin of each issue
- Your rationale for identifying these as issues
- The ways in which your proposed changes will improve the code and its workflow
- The specific problems your changes aim to resolve

Providing this information will enable both of us to use our time more efficiently and maintain a professional atmosphere. The purpose of pull request comments is to clearly communicate the intentions behind your code changes, facilitating a productive review process. I recognize that your time is valuable, and I appreciate your commitment to this project. In order to facilitate a productive and efficient review process, I kindly request that you provide the necessary information before proceeding with further comments. This will enable us to focus on addressing the key issues and ensure that our collaboration remains professional and effective.

In the interest of maintaining a professional atmosphere, I kindly request that you refrain from using emojis in our communication. Doing so will help ensure that our discussions remain focused and mature, allowing us to work more effectively together. Thank you for your understanding.

**Comment by improbably-you** [comment]
### For commander.py

**The origin of each issue:**
  - The original code lacked the functionality to read commands from a file.
  - The original code had global variables, which made the code harder to read and maintain.
  - The original code contained an unnecessary ASCII art, which is unrelated to the main functionality of the script.
  - In the original code, the argparse-related code and the main functionality were mixed together, making it harder to read and maintain.
  - The original code was missing error handling when creating a socket, which could lead to unexpected crashes.
  - The original code used the same variable names for command and target IP across different lines, making it harder to follow the logic.
  - The original code contained unnecessary conditional statements that could be simplified.

**Your rationale for identifying these as issues:**
  - Reading commands from a file is useful when a user wants to execute multiple commands without providing them one by one.
  - Refactoring the code by removing global variables and organizing the code into functions improves readability and maintainability.
  - Removing the ASCII art maintains a professional appearance and focuses on the core functionality of the script.
  - Separating the argparse-related code from the main functionality improves the code's readability and maintainability.
  - Adding error handling for socket creation prevents unexpected crashes and provides a better user experience.
  - Using distinct variable names for command and target IP improves the clarity of the code and prevents confusion.
  - Simplifying unnecessary conditional statements can improve the code's readability.


**The ways in which your proposed changes will improve the code and its workflow:**
  - The updated code includes a new function `read_commands_from_file(file_path)` to read commands from a file.
  - The updated code organizes the code into functions, such as `create_arg_parser()` and `main()`, improving the structure and making it easier to follow.
  - The updated code removes the ASCII art, keeping the focus on the functionality and maintaining a professional atmosphere.
  - The updated code refactors the argparse-related code into a separate function called `create_arg_parser()`.
  - The updated code adds error handling when creating a socket in the main() function.
  - The updated code uses different variable names for command and target IP, making it easier to understand the code's logic.
  - The updated code simplifies the conditional statements related to checking if command-line arguments are provided.

**The specific problems your changes aim to resolve:**
  - The updated code addresses the lack of functionality to read commands from a file.
  - The updated code resolves issues related to readability and maintainability by refactoring the code structure.
  - The updated code removes unnecessary ASCII art to maintain a professional appearance.
  - The updated code resolves issues related to readability and maintainability by separating argparse-related code from the main functionality.
  - The updated code addresses the lack of error handling when creating a socket, preventing unexpected crashes.
  - The updated code improves code clarity by using distinct variable names for command and target IP.
  - The updated code resolves issues related to code readability by simplifying unnecessary conditional statements.
  
### For receiver.py

**The origin of each issue**

  - In the original code, the argument parser is created and configured directly in the global scope, making it less modular.
  - In the original code, the decode function reads the 'log' from the global scope, limiting its reusability.
  - The original code lacks a main function, causing the main part of the code to be mixed with other parts, which affects code organization.
  - In the original code, the KeyboardInterrupt exception handling is done within the same try block as the subprocess, making the code harder to read.
  - The original code includes unnecessary variable initializations in the decode function, causing inefficiency.

**Your rationale for identifying these as issues**
  - Creating and configuring the argument parser directly in the global scope can make the code harder to maintain and update in the future.
  - Reading the 'log' from the global scope limits the decode function's versatility and reusability in other contexts.
  - Mixing the main part of the code with other parts can make it harder to understand the code's structure and to perform testing.
  - Combining KeyboardInterrupt exception handling with the subprocess code makes the code more difficult to understand.
  - Unnecessary variable initializations consume resources and affect the code's overall performance.

**The ways in which your proposed changes will improve the code and its workflow**
  - By using the create_arg_parser function, the code becomes more modular, making it easier to maintain and update the argument parser.
  - Passing the 'log' directly to the decode function as an argument makes it more versatile and reusable.
  - Encapsulating the main part of the code within a main function improves the code organization and allows for easier testing.
  - Separating the KeyboardInterrupt exception handling into a distinct except block makes the code more readable and understandable.
  - Removing unnecessary variable initializations in the decode function improves the code's efficiency and resource usage.

**The specific problems your changes aim to resolve**

  - The changes improve maintainability and modularity by organizing the argument parser creation and configuration into a function.
  - The changes enhance the decode function's reusability by making it independent of the global scope.
  - The changes address the code organization issue by introducing a main function, which separates the main code logic from other parts.
  - The changes improve code readability by handling the KeyboardInterrupt exception in a separate except block.
  - The changes aim to resolve inefficiency by removing unnecessary variable initializations in the decode function.

**Comment by Cyber-Guy1** [comment]
Dear @improbably-you,

Thank you for taking the time to submit a comprehensive pull request with detailed explanations regarding the issues you've identified in the code. Your focus on improving readability, maintainability, and efficiency is commendable.

While we agree that the addition of the new function for reading commands from a file is a valuable enhancement to the code, we believe that many of the other proposed changes may not significantly impact the overall usability of the code. As a result, we will focus on integrating the new function into the codebase soon.

Regarding the other issues you've mentioned, such as the removal of ASCII art and similar changes, we appreciate your input, but we believe that these modifications may not substantially improve the user experience. Instead, we will prioritize adding comments and documentation to the code, which will facilitate easier maintenance and debugging for future contributors.

We value your contribution and encourage you to continue submitting issues or pull requests related to adding new features or addressing critical issues that may affect the code's operational usability.

Thank you once again for your efforts, and please do not hesitate to reach out with further suggestions or concerns.

Best regards

**Comment by improbably-you** [comment]
I think it's cool that you're using ChatGPT to respond to me, it's very innovative. 

However, some might find it a bit impersonal and rude. While the remarks from the bot are professional in nature, they miss a number of clue-ins regarding context.

For example, you phrased your last response as an email and used the royal 'we' across the board.

**Comment by Cyber-Guy1** [comment]
Dear @improbably-you,

I think your problem is with me personally for some reason, but it's ok; nothing personally from my side except respect as you were trying to help out here. I'm not required to explain why, but I'm going just to make you understand, I'm responding with "we" as I always do in my emails and even comments, as I used to work in teams and so I used to write them whenever I remembered, but other than that, I don't know what you're talking about by "using chatGPT." If you have something personally, please discuss it with me by sending me a DM. Otherwise, please keep in mind the core usage of this function at github, which is enhancing code instead of throwing judgment. I'm sorry but I'm not going to continue this conversation as I have important things to do, best of luck.

Best regards

**Pull request closed without merging**
